# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LangLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('\u0421\u0432\u043e\u0431\u043e\u0434\u043d\u043e', '\u0421\u0432\u043e\u0431\u043e\u0434\u043d\u043e'), ('\u0423\u0432\u0435\u0440\u0435\u043d\u043d\u043e', '\u0423\u0432\u0435\u0440\u0435\u043d\u043d\u043e'), ('\u0421\u0440\u0435\u0434\u043d\u0438\u0439', '\u0421\u0440\u0435\u0434\u043d\u0438\u0439'), ('\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u0438\u0439', '\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u0438\u0439'), ('\u0411\u0430\u0437\u043e\u0432\u044b\u0439', '\u0411\u0430\u0437\u043e\u0432\u044b\u0439')], max_length=100, verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c \u0432\u043b\u0430\u0434\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0412\u043b\u0430\u0434\u0435\u043d\u0438\u0435 \u0438\u043d\u043e\u0441\u0442\u0440\u0430\u043d\u043d\u044b\u043c \u044f\u0437\u044b\u043a\u043e\u043c',
                'verbose_name_plural': '\u0412\u043b\u0430\u0434\u0435\u043d\u0438\u0435 \u0438\u043d\u043e\u0441\u0442\u0440\u0430\u043d\u043d\u044b\u043c\u0438 \u044f\u0437\u044b\u043a\u0430\u043c\u0438',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, verbose_name='\u042f\u0437\u044b\u043a')),
            ],
            options={
                'ordering': ['language'],
                'verbose_name': '\u042f\u0437\u044b\u043a',
                'verbose_name_plural': '\u042f\u0437\u044b\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=100, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('place_birth', models.CharField(blank=True, max_length=200, verbose_name='\u041c\u0435\u0441\u0442\u043e \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('sex', models.CharField(choices=[('', ''), ('\u041c', '\u041c\u0443\u0436\u0441\u043a\u043e\u0439'), ('\u0416', '\u0416\u0435\u043d\u0441\u043a\u0438\u0439')], max_length=10, verbose_name='\u041f\u043e\u043b')),
                ('photo', models.FileField(blank=True, upload_to=profiles.models.photo_path, verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
                ('address', models.CharField(max_length=300, verbose_name='\u0410\u0434\u0440\u0435\u0441')),
                ('phone', models.CharField(max_length=30, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('social_work', models.TextField(verbose_name='\u041e\u0431\u0449\u0435\u0441\u0442\u0432\u0435\u043d\u043d\u0430\u044f \u0440\u0430\u0431\u043e\u0442\u0430')),
                ('study_profile', models.CharField(choices=[('\u0425\u0438\u043c\u0438\u044f', '\u0425\u0438\u043c\u0438\u044f'), ('\u041e\u0440\u0433\u0430\u043d\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0445\u0438\u043c\u0438\u044f', '\u041e\u0440\u0433\u0430\u043d\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0445\u0438\u043c\u0438\u044f'), ('\u0411\u0438\u043e\u0445\u0438\u043c\u0438\u044f', '\u0411\u0438\u043e\u0445\u0438\u043c\u0438\u044f')], max_length=50, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f')),
                ('marital_status', models.CharField(choices=[('', ''), ('\u041d\u0435 \u0436\u0435\u043d\u0430\u0442', '\u041d\u0435 \u0436\u0435\u043d\u0430\u0442'), ('\u041d\u0435 \u0437\u0430\u043c\u0443\u0436\u0435\u043c', '\u041d\u0435 \u0437\u0430\u043c\u0443\u0436\u0435\u043c'), ('\u0416\u0435\u043d\u0430\u0442', '\u0416\u0435\u043d\u0430\u0442'), ('\u0417\u0430\u043c\u0443\u0436\u0435\u043c', '\u0417\u0430\u043c\u0443\u0436\u0435\u043c')], max_length=10, verbose_name='\u0421\u0435\u043c\u0435\u0439\u043d\u043e\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435')),
                ('notes', models.TextField(blank=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u044f')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0421\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435',
                'verbose_name_plural': '\u0421\u0432\u0435\u0434\u0435\u043d\u0438\u044f \u043e \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f\u0445',
            },
        ),
        migrations.AddField(
            model_name='langlevel',
            name='lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Language', verbose_name='\u042f\u0437\u044b\u043a'),
        ),
        migrations.AddField(
            model_name='langlevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserDetail', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
