# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='study_profile',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', ''), ('\u041d\u0435 \u0436\u0435\u043d\u0430\u0442', '\u041d\u0435 \u0436\u0435\u043d\u0430\u0442'), ('\u041d\u0435 \u0437\u0430\u043c\u0443\u0436\u0435\u043c', '\u041d\u0435 \u0437\u0430\u043c\u0443\u0436\u0435\u043c'), ('\u0416\u0435\u043d\u0430\u0442', '\u0416\u0435\u043d\u0430\u0442'), ('\u0417\u0430\u043c\u0443\u0436\u0435\u043c', '\u0417\u0430\u043c\u0443\u0436\u0435\u043c')], max_length=10, verbose_name='\u0421\u0435\u043c\u0435\u0439\u043d\u043e\u0435 \u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
