# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160626_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_professor',
            field=models.NullBooleanField(verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
