# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 23:39
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442 \u043e\u0431 \u043e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u043d\u0438\u0438', b'\xd0\x94\xd0\xbe\xd0\xba\xd1\x83\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82 \xd0\xbe\xd0\xb1 \xd0\xbe\xd0\xb1\xd1\x80\xd0\xb0\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb8'), ('\u041f\u0440\u0438\u043a\u0430\u0437', b'\xd0\x9f\xd1\x80\xd0\xb8\xd0\xba\xd0\xb0\xd0\xb7'), ('\u0420\u0430\u0441\u043f\u043e\u0440\u044f\u0436\u0435\u043d\u0438\u0435 \u0440\u0435\u043a\u0442\u043e\u0440\u0430', b'\xd0\xa0\xd0\xb0\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x8f\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5 \xd1\x80\xd0\xb5\xd0\xba\xd1\x82\xd0\xbe\xd1\x80\xd0\xb0'), ('\u0421\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442', b'\xd0\xa1\xd0\xb5\xd1\x80\xd1\x82\xd0\xb8\xd1\x84\xd0\xb8\xd0\xba\xd0\xb0\xd1\x82')], max_length=25, verbose_name='\u0422\u0438\u043f')),
                ('file', models.FileField(help_text=b'\xd0\x97\xd0\xb0\xd0\xb3\xd1\x80\xd1\x83\xd0\xb7\xd0\xb8\xd1\x82\xd0\xb5 \xd1\x81\xd0\xba\xd0\xb0\xd0\xbd \xd0\xb4\xd0\xbe\xd0\xba\xd1\x83\xd0\xbc\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb0 \xd0\xb2 \xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb5 pdf, jpg \xd0\xb8\xd0\xbb\xd0\xb8 png', upload_to=core.models.doc_path, verbose_name='\u0424\u0430\u0439\u043b')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='\u041a\u043e\u0434')),
                ('series', models.CharField(blank=True, max_length=20, verbose_name='\u0421\u0435\u0440\u0438\u044f')),
                ('number', models.CharField(max_length=20, verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('issued_by', models.CharField(max_length=100, verbose_name='\u041a\u0435\u043c \u0432\u044b\u0434\u0430\u043d')),
                ('issue_date', models.DateTimeField(max_length=20, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u0432\u044b\u0434\u0430\u043d')),
                ('issue_place', models.CharField(blank=True, max_length=20, verbose_name='\u0413\u0434\u0435 \u0432\u044b\u0434\u0430\u043d')),
                ('guideline', models.CharField(blank=True, max_length=255, verbose_name='\u0414\u0438\u0440\u0435\u043a\u0442\u0438\u0432\u0430')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserDetail', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438')),
            ],
            options={
                'ordering': ['-issue_date'],
                'verbose_name': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442',
                'verbose_name_plural': '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=100, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('title_icon_name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0438\u043a\u043e\u043d\u043a\u0438 FontAwesome')),
                ('content', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
            ],
            options={
                'verbose_name': '\u041f\u0440\u043e\u0441\u0442\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u041f\u0440\u043e\u0441\u0442\u044b\u0435 \u0441\u0440\u0430\u043d\u0438\u0446\u044b',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('issue', models.CharField(max_length=100, verbose_name='\u0418\u0437\u0434\u0430\u043d\u0438\u0435')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='\u0412 \u0438\u0437\u0434\u0430\u043d\u0438\u0438, \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u043e\u0432\u0430\u043d\u043d\u043e\u043c \u0412\u0410\u041a')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='\u0410\u0432\u0442\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u044f',
                'verbose_name_plural': '\u041f\u0443\u0431\u043b\u0438\u043a\u0430\u0446\u0438\u0438',
            },
        ),
    ]
