# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 23:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', ''), ('G', '\u0410\u0441\u043f\u0438\u0440\u0430\u043d\u0442'), ('B', '\u0411\u0430\u043a\u0430\u043b\u0430\u0432\u0440'), ('M', '\u041c\u0430\u0433\u0438\u0441\u0442\u0440'), ('S', '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442')], max_length=50, verbose_name='\u041a\u0432\u0430\u043b\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u044f/\u0441\u0442\u0435\u043f\u0435\u043d\u044c')),
                ('form', models.CharField(choices=[('', ''), ('F', '\u041e\u0447\u043d\u0430\u044f'), ('E', '\u0412\u0435\u0447\u0435\u0440\u043d\u044f\u044f'), ('C', '\u0417\u0430\u043e\u0447\u043d\u0430\u044f')], max_length=50, verbose_name='\u0424\u043e\u0440\u043c\u0430 \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f')),
                ('enter_date', models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0437\u0430\u0447\u0438\u0441\u043b\u0435\u043d\u0438\u044f')),
                ('record_book_number', models.CharField(default=0, max_length=7, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u0447\u0435\u0442\u043a\u0438')),
                ('group', models.CharField(max_length=10, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
                ('scientific_work', models.CharField(blank=True, max_length=300, verbose_name='\u041d\u0430\u0443\u0447\u043d\u0430\u044f \u0434\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c')),
                ('supervisor', models.CharField(max_length=200, verbose_name='\u0420\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
                ('status', models.CharField(choices=[('IN', '\u0417\u0430\u0447\u0438\u0441\u043b\u0435\u043d \u0432 \u0412\u0423\u0417'), ('OUT', '\u041e\u0442\u0447\u0438\u0441\u043b\u0435\u043d \u0438\u0437 \u0412\u0423\u0417\u0430')], max_length=200, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('end_date', models.DateField(null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0447\u0438\u0441\u043b\u0435\u043d\u0438\u044f')),
                ('end_reason', models.CharField(blank=True, choices=[('', ''), ('\u0423\u0441\u043f\u0435\u0448\u043d\u043e \u0437\u0430\u0432\u0435\u0440\u0448\u0438\u043b \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u0435', '\u0423\u0441\u043f\u0435\u0448\u043d\u043e \u0437\u0430\u0432\u0435\u0440\u0448\u0438\u043b \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u0435'), ('\u041e\u0442\u0447\u0438\u0441\u043b\u0435\u043d \u0437\u0430 \u043d\u0435\u0443\u0441\u043f\u0435\u0432\u0430\u0435\u043c\u043e\u0441\u0442\u044c', '\u041e\u0442\u0447\u0438\u0441\u043b\u0435\u043d \u0437\u0430 \u043d\u0435\u0443\u0441\u043f\u0435\u0432\u0430\u0435\u043c\u043e\u0441\u0442\u044c')], max_length=50, verbose_name='\u041f\u0440\u0438\u0447\u0438\u043d\u0430 \u043e\u0442\u0447\u0438\u0441\u043b\u0435\u043d\u0438\u044f')),
                ('notes', models.TextField(blank=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ['user__userdetail__last_name'],
                'verbose_name': '\u041e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u041e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u043d\u0438\u0435',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('abbr', models.CharField(blank=True, max_length=20, verbose_name='\u0410\u0431\u0431\u0440\u0435\u0432\u0438\u0430\u0442\u0443\u0440\u0430')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='\u041a\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442',
                'verbose_name_plural': '\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='\u041a\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0447\u0438\u0441\u043b\u043e \u043e\u0442 1 \u0434\u043e 5', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='\u041a\u0443\u0440\u0441')),
                ('semester', models.CharField(choices=[('\u041e\u0441\u0435\u043d\u043d\u0438\u0439', '\u041e\u0441\u0435\u043d\u043d\u0438\u0439'), ('\u0412\u0435\u0441\u0435\u043d\u043d\u0438\u0439', '\u0412\u0435\u0441\u0435\u043d\u043d\u0438\u0439')], max_length=100, verbose_name='\u0421\u0435\u043c\u0435\u0441\u0442\u0440')),
                ('hour_sem', models.CharField(blank=True, max_length=40, verbose_name='\u0427\u0430\u0441/\u0421\u0435\u043c')),
                ('rating', models.IntegerField(blank=True, help_text='\u0412\u0432\u0435\u0434\u0438\u0442\u0435 \u0447\u0438\u0441\u043b\u043e \u043e\u0442 0 \u0434\u043e 100', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='\u0420\u0435\u0439\u0442\u0438\u043d\u0433')),
                ('grade', models.CharField(blank=True, choices=[('\u041e\u0442\u043b\u0438\u0447\u043d\u043e', '\u041e\u0442\u043b\u0438\u0447\u043d\u043e'), ('\u0425\u043e\u0440\u043e\u0448\u043e', '\u0425\u043e\u0440\u043e\u0448\u043e'), ('\u0423\u0434\u043e\u0432\u043b.', '\u0423\u0434\u043e\u0432\u043b.'), ('\u0417\u0430\u0447\u0435\u0442', '\u0417\u0430\u0447\u0435\u0442'), ('\u041d\u0435\u0437\u0430\u0447\u0435\u0442', '\u041d\u0435\u0437\u0430\u0447\u0435\u0442')], max_length=40, verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430')),
                ('leaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Education')),
            ],
            options={
                'ordering': ['course', '-semester', 'subject__name'],
                'verbose_name': '\u0423\u0441\u043f\u0435\u0432\u0430\u0435\u043c\u043e\u0441\u0442\u044c',
                'verbose_name_plural': '\u0423\u0441\u043f\u0435\u0432\u0430\u0435\u043c\u043e\u0441\u0442\u044c',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='\u041a\u043e\u0434')),
                ('prk', models.CharField(blank=True, max_length=20, verbose_name='\u041f\u0440\u041a')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u0414\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u0430',
                'verbose_name_plural': '\u0414\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='TrainingField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='\u041a\u043e\u0434')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0435 \u043f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0438',
                'verbose_name_plural': '\u041d\u0430\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f \u043f\u043e\u0434\u0433\u043e\u0442\u043e\u0432\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='\u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: \u041a\u0432\u0430\u043b\u0438\u0444\u0438\u043a\u0430\u0446\u0438\u043e\u043d\u043d\u0430\u044f \u0440\u0430\u0431\u043e\u0442\u0430 \u0431\u0430\u043a\u0430\u043b\u0430\u0432\u0440\u0430', max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('is_graduation', models.BooleanField(default=False, verbose_name='\u0420\u0430\u0431\u043e\u0442\u0430 \u044f\u0432\u043b\u044f\u0435\u0442\u0441\u044f \u0432\u044b\u043f\u0443\u0441\u043a\u043d\u043e\u0439')),
                ('theme', models.CharField(help_text='\u0423\u043a\u0430\u0436\u0438\u0442\u0435 \u0442\u0435\u043c\u0443 \u0411\u0415\u0417 \u043a\u0430\u0432\u044b\u0447\u0435\u043a', max_length=255, verbose_name='\u0422\u0435\u043c\u0430 \u0440\u0430\u0431\u043e\u0442\u044b')),
                ('file', models.FileField(help_text='\u0417\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u0435 \u0441\u043a\u0430\u043d \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u0430 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435 pdf, jpg \u0438\u043b\u0438 png', upload_to=education.models.work_path, verbose_name='\u0424\u0430\u0439\u043b')),
                ('date', models.DateTimeField(max_length=20, verbose_name='\u0414\u0430\u0442\u0430 \u043d\u0430\u043f\u0438\u0441\u0430\u043d\u0438\u044f')),
                ('place', models.CharField(blank=True, max_length=20, verbose_name='\u0413\u0434\u0435 \u043d\u0430\u043f\u0438\u0441\u0430\u043d\u0430')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Education')),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name': '\u0420\u0430\u0431\u043e\u0442\u0430',
                'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='studies',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Subject', verbose_name='\u0414\u0438\u0441\u0446\u0438\u043f\u043b\u0438\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='education',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Faculty', verbose_name='\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442'),
        ),
        migrations.AddField(
            model_name='education',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Speciality', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
