# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair', to='locations.Department', verbose_name='\u041a\u0430\u0444\u0435\u0434\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='education',
            name='study_profile',
            field=models.CharField(blank=True, choices=[('\u0425\u0438\u043c\u0438\u044f', '\u0425\u0438\u043c\u0438\u044f'), ('\u041e\u0440\u0433\u0430\u043d\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0445\u0438\u043c\u0438\u044f', '\u041e\u0440\u0433\u0430\u043d\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u0445\u0438\u043c\u0438\u044f'), ('\u0411\u0438\u043e\u0445\u0438\u043c\u0438\u044f', '\u0411\u0438\u043e\u0445\u0438\u043c\u0438\u044f')], max_length=50, verbose_name='\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u043e\u0431\u0443\u0447\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='locations.Department', verbose_name='\u0424\u0430\u043a\u0443\u043b\u044c\u0442\u0435\u0442'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
