# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20160627_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Department', verbose_name='\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u0435 (\u041a\u0430\u0444\u0435\u0434\u0440\u0430)'),
        ),
    ]
