# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('abbr', models.CharField(blank=True, max_length=20, verbose_name='\u0410\u0431\u0431\u0440\u0435\u0432\u0438\u0430\u0442\u0443\u0440\u0430')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='\u041a\u043e\u0434')),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Department')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u044f',
            },
        ),
    ]
